language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
addons:
  apt:
    packages:
      - gfortran
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - libgmp-dev
      - libglpk-dev
      - libmpfr-dev

# command to install dependencies
env:
  - PIP_CACHE_DIR=$HOME/.cache/pip
before_install:
  - pip install pip --upgrade
  # These get cached
  - pip install numpy scipy python-libsbml -v  # verbose for long-running compiles
  - pip install cython coveralls jsonschema six pandas matplotlib jupyter
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install lxml glpk pep8; fi
  # Download esolver and add it to the path
  - wget https://opencobra.github.io/pypi_cobrapy_travis/esolver.gz
  - gzip -d esolver.gz; chmod +x esolver; export PATH=$PATH:$PWD
install:
  - python setup.py develop
# # command to run tests
script:
  - coverage run --source=cobra setup.py test
  - coverage run --source=cobra jupyter-nbconvert --ExecutePreprocessor.enabled=True \
      documentation_builder/phenotype_phase_plane.ipynb \
      documentation_builder/getting_started.ipynb \
      documentation_builder/simulating.ipynb \
      documentation_builder/deletions.ipynb \
      documentation_builder/faq.ipynb \
      documentation_builder/building_model.ipynb
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then
    pep8 cobra/core cobra/design cobra/manipulation cobra/test cobra/version.py;
    fi
after_success:
  - coveralls
